### ISSUE TITLE
name disappears when you resize the page to be small

### ISSUE THREAD

**Issue by sadienicole** [sadienicole/personal-website#1]
<img width="493" alt="Screen Shot 2022-04-04 at 7 57 38 AM" src="https://user-images.githubusercontent.com/24860565/161572155-c35593d1-033f-4652-9cfc-7655e0a66418.png">

I would ultimately prefer that they stack on top of each other in extreme cases like this.

**Comment by hs-07** [comment]
hello sadie!! 
i went the your personal website, and found it a unique one.
ya ! its not responsive that why you are facing such issue.
assign me the issue, i can easily fix this.

**Comment by sadienicole** [comment]
@hs-07 I have assigned you the issue, thanks so much for the help!

**Comment by hs-07** [comment]
oh!! thanks ... i would love to help you .
